project:
  type: website

website:
  description: "Data Science Portfolio"
  site-url: https://TheSalocin.github.io # update with your GitHub username
  title: "Nicolas Patzlaff"
  navbar:
    background: dark
    foreground: light
    right:
      - text: "Blog"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/TheSalocin
      - icon: linkedin
        href: https://www.linkedin.com/in/nicolas-patzlaff-72b02b22b/

format:
  html:
    theme: cyborg
    css: styles.css
    highlight-style: dracula



